# Generated by Django 5.1.1 on 2024-10-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                default="profil.png", upload_to="", verbose_name="Photo de profil"
            ),
        ),
    ]
