# Generated by Django 5.1 on 2024-09-30 10:50

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cellule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DossierJour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                ("fichier", models.FileField(upload_to="media/")),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cellule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archives.cellule",
                    ),
                ),
            ],
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="cellule",
            name="dossier_jour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="archives.dossierjour"
            ),
        ),
    ]
