# Generated by Django 5.1.1 on 2024-09-28 23:47

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="archive",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
    ]
