# Generated by Django 5.1.1 on 2024-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierjour',
            name='count_in_other_table',
            field=models.IntegerField(default=0),
        ),
    ]
