# Generated by Django 5.1.1 on 2024-10-21 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0003_alter_dossierjour_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierjour",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 10, 21, 0, 32, 3, 575148, tzinfo=datetime.timezone.utc
                ),
                unique=True,
            ),
        ),
    ]
