# Generated by Django 5.1.1 on 2024-10-21 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0004_alter_dossierjour_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierjour",
            name="date",
            field=models.DateField(default=datetime.date(2024, 10, 21), unique=True),
        ),
    ]
